---

name: resumedeploy

on:
  workflow_run:
    workflows: ["resumechecks"]
    branches: ["main"]
    types:
      - completed

jobs:

  resumedeploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: Checking out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          check-latest: true

      - name: Install npm packages
        run: npm --prefix resume install
        env:
          PUPPETEER_SKIP_DOWNLOAD: 1

      - name: Run generate resume html
        run: npm --prefix resume run build:html

      - name: Commit resume file
        run: |
          git add resume/index.html
          git stash
          git checkout gh-pages
          git checkout stash -- resume/index.html
          if git status | grep -q 'resume/index.html'; then
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add resume/index.html
              git commit -m "chore: update resume"
              git push
          else
              echo "Nothing to do - Resume up to date"
          fi
