---

name: resume

on:
  workflow_run:
    workflows: ["resumechecks"]
    branches: ["main"]
    types:
      - completed

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install chromium
        run: sudo apt-get update && sudo apt-get -y install chromium-browser
      - name: Install npm packages
        run: npm --prefix resume install
      - name: Run generate resume html
        run: npm --prefix resume run build:html
        env:
          RESUME_PUPPETEER_NO_SANDBOX: 1
      - name: Commit resume file
        run: |
          git add resume/index.html
          git stash
          git checkout gh-pages
          rm -rvf resume/index.html
          git stash apply
          git status | grep 'resume/index.html'
          if [ $? -eq 0 ];then
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add resume/index.html
              git commit -m "chore: update resume"
              git push
          fi
