---

name: resumechecks

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/resume*yaml'
      - '.cspell/*'
      - 'resume/*'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/resume*yaml'
      - '.cspell/*'
      - 'resume/*'
  workflow_dispatch:

jobs:

  resumevalidate:
    runs-on: ubuntu-latest
    steps:

      - name: Checking out repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Install npm packages
        run: npm --prefix resume install

      - name: Run validation
        run: npm --prefix resume run validate

  resumespellcheck:
    runs-on: ubuntu-latest
    steps:

      - name: Checking out repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true

      - name: Install npm packages
        run: npm --prefix .cspell install

      - name: Check spelling
        run: npm --prefix .cspell run spellcheck:resume
