---

name: webchecks

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/web*yaml'
      - '.cspell/**'
      - '.gitmodules'
      - 'config.yaml'
      - 'static/**'
      - 'content/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - '.github/workflows/web*yaml'
      - '.cspell/**'
      - '.gitmodules'
      - 'config.yaml'
      - 'static/**'
      - 'content/**'
  workflow_dispatch:


jobs:

  webspellcheck:
    runs-on: ubuntu-latest
    steps:

      - name: Checking out repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          check-latest: true

      - name: Install npm packages
        run: npm --prefix .cspell install

      - name: Check spelling
        run: npm --prefix .cspell run spellcheck:web
